<a href="https://colab.research.google.com/github/aleszcz/Aleks_portfolio/blob/main/HM4_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

# Define the matrix
matrix_A = np.array([[2, 0],
                     [0, 5]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_A)

# Print the results
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 5.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]


In [9]:
import numpy as np

# Define the matrix
matrix_A = np.array([[4, 1, 6],
                    [0, 2, 3],
                    [0, 0, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_A)

# Print the results
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[4. 2. 9.]

Eigenvectors:
[[ 1.         -0.4472136   0.76337004]
 [ 0.          0.89442719  0.25445668]
 [ 0.          0.          0.59373225]]


In [10]:
import numpy as np

# Define the matrix
matrix_A = np.array([[1, 4, 0, 0],
                    [0, 2, 0, 0],
                    [4, 5, 1, 1],
                    [4, 7, 2, 2]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_A)

# Print the results
print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[0. 3. 1. 2.]

Eigenvectors:
[[ 0.00000000e+00  0.00000000e+00  2.42535625e-01  1.15206341e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.88015853e-02]
 [-7.07106781e-01 -4.47213595e-01 -2.17031968e-17 -3.31218231e-01]
 [ 7.07106781e-01 -8.94427191e-01 -9.70142500e-01 -9.36051522e-01]]


In [ ]:
#No, the concept of eigenvalues and eigenvectors is specifically defined for square matrices. In linear algebra, a square matrix is a matrix with an equal number of rows and columns.

In [11]:
#SVD
import numpy as np

# Define the matrix
matrix_A = np.array([[5, 7, 21, 32],
                    [0, 3, 43, 24],
                    [2, 36, 95, 84],
                    [92, 37, 57, 64]])

# Calculate SVD
U, Sigma, Vt = np.linalg.svd(matrix_A)

# Print the results
print("Matrix U:")
print(U)

print("\nMatrix Sigma (Diagonal matrix):")
print(np.diag(Sigma))

print("\nMatrix V transpose:")
print(Vt)


Matrix U:
[[-0.20468979 -0.10450951 -0.51344003 -0.82677638]
 [-0.24019891 -0.2628848   0.8325511  -0.42432856]
 [-0.68596945 -0.59544671 -0.19825567  0.36821708]
 [-0.65563137  0.7519392   0.06271115  0.02832426]]

Matrix Sigma (Diagonal matrix):
[[181.08950358   0.           0.           0.        ]
 [  0.          73.81513152   0.           0.        ]
 [  0.           0.          14.85458672   0.        ]
 [  0.           0.           0.           8.32221756]]

Matrix V transpose:
[[-0.34631203 -0.28221783 -0.64700119 -0.61790819]
 [ 0.91397203  0.06591396 -0.36856466 -0.15643072]
 [ 0.18887868 -0.39808031  0.65688152 -0.61185258]
 [-0.09512076  0.87036804  0.11855891 -0.46835383]]


In [12]:
import numpy as np

# Define the matrix
original_matrix = np.array([[5, 7, 21, 32],
                            [0, 3, 43, 24],
                            [2, 36, 95, 84],
                            [92, 37, 57, 64]])

# Compute SVD
U, Sigma, Vt = np.linalg.svd(original_matrix, full_matrices=True)

# Diagonal matrix from Sigma values
Sigma_matrix = np.diag(Sigma)

# Verify by multiplying U, Sigma, and Vt
reconstructed_matrix = np.dot(U, np.dot(Sigma_matrix, Vt))

# Print the results
print("Original Matrix:")
print(original_matrix)

print("\nU Matrix:")
print(U)

print("\nSigma Matrix:")
print(Sigma_matrix)

print("\nVt Matrix:")
print(Vt)

print("\nReconstructed Matrix:")
print(reconstructed_matrix)


Original Matrix:
[[ 5  7 21 32]
 [ 0  3 43 24]
 [ 2 36 95 84]
 [92 37 57 64]]

U Matrix:
[[-0.20468979 -0.10450951 -0.51344003 -0.82677638]
 [-0.24019891 -0.2628848   0.8325511  -0.42432856]
 [-0.68596945 -0.59544671 -0.19825567  0.36821708]
 [-0.65563137  0.7519392   0.06271115  0.02832426]]

Sigma Matrix:
[[181.08950358   0.           0.           0.        ]
 [  0.          73.81513152   0.           0.        ]
 [  0.           0.          14.85458672   0.        ]
 [  0.           0.           0.           8.32221756]]

Vt Matrix:
[[-0.34631203 -0.28221783 -0.64700119 -0.61790819]
 [ 0.91397203  0.06591396 -0.36856466 -0.15643072]
 [ 0.18887868 -0.39808031  0.65688152 -0.61185258]
 [-0.09512076  0.87036804  0.11855891 -0.46835383]]

Reconstructed Matrix:
[[ 5.00000000e+00  7.00000000e+00  2.10000000e+01  3.20000000e+01]
 [-1.66660416e-15  3.00000000e+00  4.30000000e+01  2.40000000e+01]
 [ 2.00000000e+00  3.60000000e+01  9.50000000e+01  8.40000000e+01]
 [ 9.20000000e+01  3.70000000

In [13]:
import numpy as np

A = np.array([[5, 7, 21, 32],
              [0, 3, 43, 24],
              [2, 36, 95, 84],
              [92, 37, 57, 64]])

A[0, :] = A[1, :] + A[2, :]  # Make the first row the sum of the 2nd and 3rd rows
A[-1, :] = A[1, :]           # Make the last row the same as the 2nd row

print(A)

[[  2  39 138 108]
 [  0   3  43  24]
 [  2  36  95  84]
 [  0   3  43  24]]


In [ ]:
U, S, V = np.linalg.svd(A)
print(A)

[[  2  39 138 108]
 [  0   3  43  24]
 [  2  36  95  84]
 [  0   3  43  24]]


In [ ]:
# Why the last 2 values of the ‘Sigma’ matrix values are zeros
#result of the rank deficiency of the modified matrix A. In this case, the last two rows of the matrix are linearly dependent on the first two rows.
# When performing SVD, the singular values in the Sigma matrix represent the magnitude of the singular vectors.
#If there are fewer non-zero singular values than the size of the matrix, it indicates that the matrix has less than full rank.

In [ ]:
#In this specific example, the last two singular values are zero because the matrix A is rank-deficient.
#The zero singular values indicate that there are linear dependencies in the rows (or columns) of the matrix, and this results in a lower-rank representation.
#The rank of a matrix indicates how many of these rows (or columns) are independent, meaning they provide unique information.
#Having a lower rank suggests that there is less diversity or independence among the rows (or columns) of the matrix.

In [21]:
#rectangal matrix
import numpy as np
A = np.array([[3, 1, 1],[-1,3,1]])
#B = np.array ([[1, 1],[0, 1],[-1, 1]])
print(A)
#print(B)


[[ 3  1  1]
 [-1  3  1]]


In [22]:
#compute AtA and AAT  to get Square
ATA= np.dot(A.T,A)
AAT = np.dot(A,A.T)
print('ATA')
print(ATA)

print('AAT')
print(AAT)

ATA
[[10  0  2]
 [ 0 10  4]
 [ 2  4  2]]
AAT
[[11  1]
 [ 1 11]]


In [24]:
from scipy.linalg import eig
#compute Eigen vectors and values of ATA

# Assuming ATA is defined earlier in your code
values, vectors = eig(ATA)
print()
print(values)
print()
print(vectors)



[ 0.+0.j 10.+0.j 12.+0.j]

[[ 1.82574186e-01 -8.94427191e-01 -4.08248290e-01]
 [ 3.65148372e-01  4.47213595e-01 -8.16496581e-01]
 [-9.12870929e-01  5.07704275e-16 -4.08248290e-01]]


In [26]:
#decompose of ATA again
# A = P*D*Transpose(P)
# is matrix columns are eigien vectors of A and D i diagonal matrix of eigen values of A along the diagonal

r= np.dot(vectors, np.diag(values))
recreated = np.dot(r,vectors.T)
print('REcreated Matrix =')
print('Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)')
print(recreated)
print()
print('Original Matrix =\n',ATA)


REcreated Matrix =
Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)
[[1.00000000e+01+0.j 3.86082910e-15+0.j 2.00000000e+00+0.j]
 [4.40472508e-15+0.j 1.00000000e+01+0.j 4.00000000e+00+0.j]
 [2.00000000e+00+0.j 4.00000000e+00+0.j 2.00000000e+00+0.j]]

Original Matrix =
 [[10  0  2]
 [ 0 10  4]
 [ 2  4  2]]


In [27]:
#Compute Eigen vector AAT
values, vectors= eig(AAT)

print()
print(values)
print()
print(vectors)


[12.+0.j 10.+0.j]

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [38]:
#decompose AAT

r= np.dot(vectors, np.diag(values))
recreated = np.dot(r,vectors.T)
print('REcreated Matrix =')
print('Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)')
print(recreated)
print()
print('Original Matrix =\n',AAT)

REcreated Matrix =
Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)
[[11.+0.j  1.+0.j]
 [ 1.+0.j 11.+0.j]]

Original Matrix =
 [[11  1]
 [ 1 11]]


In [39]:
#compute SVD of REctangle matrix
np.set_printoptions( precision = 4, suppress=True)
from scipy.linalg import svd


In [40]:
V, Sigma, UStar = svd (A)
print(V, "\n\n", Sigma, "\n\n", UStar)


[[-0.7071 -0.7071]
 [-0.7071  0.7071]] 

 [3.4641 3.1623] 

 [[-0.4082 -0.8165 -0.4082]
 [-0.8944  0.4472  0.    ]
 [-0.1826 -0.3651  0.9129]]


In [41]:
#computing back to the orgiginal maatrix back

sigmaMatrix = np.diag(Sigma)
print('Sigma Matrix \n', sigmaMatrix)

Sigma Matrix 
 [[3.4641 0.    ]
 [0.     3.1623]]


In [42]:
#apply zeros to get rectangular matrix-tricks
z= np.zeros((2,1))
sigmaMatrix_extended = np.hstack((sigmaMatrix,z))
print(sigmaMatrix)


[[3.4641 0.    ]
 [0.     3.1623]]


In [47]:
#Verification of SVD original rectangular MAtrix
res = np.dot (V,sigmaMatrix_extended)
recreateA = np.dot(res,UStar)
print( '\nREcreated Matrix A \n',recreateA)
print('\nOriginal Matrix A \n', A)
print()


REcreated Matrix A 
 [[ 3.  1.  1.]
 [-1.  3.  1.]]

Original Matrix A 
 [[ 3  1  1]
 [-1  3  1]]



In [74]:
#rectangal matrix B
import numpy as np
#A = np.array([[3, 1, 1],[-1,3,1]])
A = np.array ([[1, 1],[0, 1],[-1, 1]])
print(A)

[[ 1  1]
 [ 0  1]
 [-1  1]]


In [75]:
#compute AtA and AAT  to get Square
ATA= np.dot(A.T,A)
AAT = np.dot(A,A.T)
print('ATA')
print(ATA)

print('AAT')
print(AAT)

ATA
[[2 0]
 [0 3]]
AAT
[[2 1 0]
 [1 1 1]
 [0 1 2]]


In [76]:
from scipy.linalg import eig
#compute Eigen vectors and values of ATA

# Assuming ATA is defined earlier in your code
values, vectors = eig(ATA)
print()
print(values)
print()
print(vectors)



[2.+0.j 3.+0.j]

[[1. 0.]
 [0. 1.]]


In [77]:
#decompose of ATA again
# A = P*D*Transpose(P)
# is matrix columns are eigien vectors of A and D i diagonal matrix of eigen values of A along the diagonal

r= np.dot(vectors, np.diag(values))
recreated = np.dot(r,vectors.T)
print('REcreated Matrix =')
print('Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)')
print(recreated)
print()
print('Original Matrix =\n',ATA)


REcreated Matrix =
Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)
[[2.+0.j 0.+0.j]
 [0.+0.j 3.+0.j]]

Original Matrix =
 [[2 0]
 [0 3]]


In [78]:
#Compute Eigen vector and value AAT
values, vectors= eig(AAT)

print()
print(values)
print()
print(vectors)


[-0.+0.j  2.+0.j  3.+0.j]

[[ 0.4082  0.7071  0.5774]
 [-0.8165  0.      0.5774]
 [ 0.4082 -0.7071  0.5774]]


In [87]:
#decompose AAT

r= np.dot(vectors, np.diag(values))
recreated = np.dot(r,vectors.T)
print('REcreated Matrix =')
print('Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)')
print(recreated)
print()
print('Original Matrix =\n',AAT)

REcreated Matrix =
Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)
[[2.+0.j 1.+0.j 0.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [0.+0.j 1.+0.j 2.+0.j]]

Original Matrix =
 [[2 1 0]
 [1 1 1]
 [0 1 2]]


In [89]:
import numpy as np
from scipy.linalg import eig

# Compute AAT
AAT = np.dot(A, A.T)

# Compute eigenvalues and eigenvectors of AAT
values, vectors = eig(AAT)

# Reconstruct AAT
reconstructed = np.dot(np.dot(vectors, np.diag(values)), np.linalg.inv(vectors))

# Display the results
print("Reconstructed Matrix:")
print(reconstructed)
print("\nOriginal Matrix (AAT):")
print(AAT)


Reconstructed Matrix:
[[ 2.+0.j  1.+0.j  0.+0.j]
 [ 1.+0.j  1.+0.j  1.+0.j]
 [-0.+0.j  1.+0.j  2.+0.j]]

Original Matrix (AAT):
[[2 1 0]
 [1 1 1]
 [0 1 2]]


In [90]:
#compute SVD of REctangle matrix
np.set_printoptions( precision = 4, suppress=True)
from scipy.linalg import svd


In [91]:
V, Sigma, UStar = svd (A)
print(V, "\n\n", Sigma, "\n\n", UStar)


[[-0.5774 -0.7071  0.4082]
 [-0.5774  0.     -0.8165]
 [-0.5774  0.7071  0.4082]] 

 [1.7321 1.4142] 

 [[-0. -1.]
 [-1. -0.]]


In [92]:
#computing back to the orgiginal maatrix back

sigmaMatrix = np.diag(Sigma)
print('Sigma Matrix \n', sigmaMatrix)

Sigma Matrix 
 [[1.7321 0.    ]
 [0.     1.4142]]


In [93]:
#apply zeros to get rectangular matrix-tricks
z= np.zeros((2,1))
sigmaMatrix_extended = np.hstack((sigmaMatrix,z))
print(sigmaMatrix)


[[1.7321 0.    ]
 [0.     1.4142]]


In [95]:
import numpy as np
from scipy.linalg import svd

A = np.array([[1, 1],
              [0, 1],
              [-1, 1]])

# Compute SVD
U, Sigma, Vt = svd(A)

# Extend Sigma to make it rectangular
z = np.zeros((2, 1))
sigmaMatrix_extended = np.hstack((np.diag(Sigma), z))

# Verification of SVD
res = np.dot(Vt.T, sigmaMatrix_extended)
recreateA = np.dot(res, U.T)

# Display the results
print("Recreated Matrix A:")
print(recreateA)
print("\nOriginal Matrix A:")
print(A)


Recreated Matrix A:
[[ 1.  0. -1.]
 [ 1.  1.  1.]]

Original Matrix A:
[[ 1  1]
 [ 0  1]
 [-1  1]]


In [127]:
#Verification of SVD original rectangular MAtrix


#rectangal matrix B
import numpy as np
#A = np.array([[3, 1, 1],[-1,3,1]])
A = np.array ([[1, 1],[0, 1],[-1, 1]])
print(A)


#compute AtA and AAT  to get Square
ATA= np.dot(A.T,A)
AAT = np.dot(A,A.T)
print('ATA')
print(ATA)

print('AAT')
print(AAT)


from scipy.linalg import eig
#compute Eigen vectors and values of ATA

# Assuming ATA is defined earlier in your code
values, vectors = eig(ATA)
print()
print(values)
print()
print(vectors)

#decopm ATA

r= np.dot(vectors, np.diag(values))
recreated = np.dot(r,vectors.T)
print('REcreated Matrix =')
print('Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)')
print(recreated)
print()
print('Original Matrix =\n',ATA)


#Compute Eigen vector and value AAT
values, vectors= eig(AAT)

print()
print(values)
print()
print(vectors)

#decompose AAT

r= np.dot(vectors, np.diag(values))
recreated = np.dot(r,vectors.T)
print('REcreated Matrix =')
print('Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)')
print(recreated)
print()
print('Original Matrix =\n',AAT)


#compute SVD of REctangle matrix
np.set_printoptions( precision = 4, suppress=True)
from scipy.linalg import svd


V, Sigma, UStar = svd (A)
print(V, "\n\n", Sigma, "\n\n", UStar)

sigmaMatrix = np.diag(Sigma)
print('Sigma MAtrix \n', sigmaMatrix)


z= np.zeros((1,3))
sigmaMatrix_extended = np.hstack((sigmaMatrix,z))
print(sigmaMatrix_extended)


res = np.dot(V,sigmaMatrix_extended)
print(res)
recreateA = np.dot(res,UStar)
print( '\nREcreated Matrix A \n',recreateA)
print('\nOriginal Matrix A \n', A)
print()

[[ 1  1]
 [ 0  1]
 [-1  1]]
ATA
[[2 0]
 [0 3]]
AAT
[[2 1 0]
 [1 1 1]
 [0 1 2]]

[2.+0.j 3.+0.j]

[[1. 0.]
 [0. 1.]]
REcreated Matrix =
Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)
[[2.+0.j 0.+0.j]
 [0.+0.j 3.+0.j]]

Original Matrix =
 [[2 0]
 [0 3]]

[-0.+0.j  2.+0.j  3.+0.j]

[[ 0.4082  0.7071  0.5774]
 [-0.8165  0.      0.5774]
 [ 0.4082 -0.7071  0.5774]]
REcreated Matrix =
Eigen Vectors * Eigen Vlues * Transpose(Eigen Vectors)
[[2.+0.j 1.+0.j 0.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [0.+0.j 1.+0.j 2.+0.j]]

Original Matrix =
 [[2 1 0]
 [1 1 1]
 [0 1 2]]
[[-0.5774 -0.7071  0.4082]
 [-0.5774  0.     -0.8165]
 [-0.5774  0.7071  0.4082]] 

 [1.7321 1.4142] 

 [[-0. -1.]
 [-1. -0.]]
Sigma MAtrix 
 [[1.7321 0.    ]
 [0.     1.4142]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [86]:
import numpy as np
from scipy.linalg import eig

A = np.array([[1, 1],
              [0, 1],
              [-1, 1]])

# Compute AAT
AAT = np.dot(A, A.T)

# Compute eigenvalues and eigenvectors
values, vectors = eig(AAT)

# Reconstruct the original matrix AAT
reconstructed_AAT = np.dot(np.dot(vectors, np.diag(values)), vectors.T)

# Display the results
print('Reconstructed Matrix:')
print(reconstructed_AAT)
print('\nOriginal Matrix:')
print(AAT)


Reconstructed Matrix:
[[2.+0.j 1.+0.j 0.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [0.+0.j 1.+0.j 2.+0.j]]

Original Matrix:
[[2 1 0]
 [1 1 1]
 [0 1 2]]


In [ ]:
# Using the Singular Value Decomposition (SVD) principals, perform the Latent Semantics Analysis
# (LSA) of the following 6 documents. Divide these documents into 2 different topics.

#1. 'runs',
#2. 'runs pitcher innings',
#3. 'pitcher',
#4. 'touchdown',
#5. 'quarterback',
#6. 'touchdown quarterback'
#Use the following 2 libraries to solve this problem.
# from sklearn.feature_extraction.text import CountVectorizer

# from sklearn.decomposition import TruncatedSVD