<a href="https://colab.research.google.com/github/aleszcz/Aleks_portfolio/blob/main/Transformers_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#BERT and transformers

In [ ]:
import numpy as np
np.set_printoptions(precision=5, suppress=True)

In [ ]:
num_Words = 3
embedding_dim = 4
Xword2vec = np.array ([[1.769, 2.22, 3.4, 5.8],[7.3, 9.9, 8.5, 7.1],[9.1, 7.1, 0.85, 10.1]])
print (Xword2vec)

[[ 1.769  2.22   3.4    5.8  ]
 [ 7.3    9.9    8.5    7.1  ]
 [ 9.1    7.1    0.85  10.1  ]]


In [ ]:

#computing possitional encoding
pos_encoding = np.zeros((num_Words,embedding_dim))

for i in range(num_Words):
  for j in  range(0, embedding_dim,2):
    pos_encoding[i,j] = np.sin(i/10000**(2*j/embedding_dim))
    pos_encoding[i, j+1] = np.cos(i/(10000**(2*j/embedding_dim)))
print(pos_encoding)
print(pos_encoding.shape)


[[ 0.       1.       0.       1.     ]
 [ 0.84147  0.5403   0.0001   1.     ]
 [ 0.9093  -0.41615  0.0002   1.     ]]
(3, 4)


In [ ]:
BERTword2vec = Xword2vec + pos_encoding
print(BERTword2vec)


[[ 1.769    3.22     3.4      6.8    ]
 [ 8.14147 10.4403   8.51     8.09995]
 [10.0093   6.68385  0.87    11.0998 ]]


In [ ]:
import numpy as np

np.set_printoptions(precision=5, suppress=True)
num_words = 3
embedding_dim = 4
Xword2vec = np.array([[1.769, 2.22, 3.4, 5.8], [7.3, 9.9, 8.5, 7.1], [9.1, 7.1, 0.85, 10.1]])
print(Xword2vec)  # computing positional encoding
pos_encoding = np.zeros((num_words, embedding_dim))

for i in range(num_words):
    for j in range(embedding_dim // 2):
        pos_encoding[i, 2*j] = np.sin(i / (10000 ** (2*j / embedding_dim)))
        pos_encoding[i, 2*j+1] = np.cos(i / (10000 ** (2*j / embedding_dim)))
print(pos_encoding)
print(pos_encoding.shape)
BERTword2vec = Xword2vec + pos_encoding
print(BERTword2vec)


[[ 1.769  2.22   3.4    5.8  ]
 [ 7.3    9.9    8.5    7.1  ]
 [ 9.1    7.1    0.85  10.1  ]]
[[ 0.       1.       0.       1.     ]
 [ 0.84147  0.5403   0.01     0.99995]
 [ 0.9093  -0.41615  0.02     0.9998 ]]
(3, 4)
[[ 1.769    3.22     3.4      6.8    ]
 [ 8.14147 10.4403   8.51     8.09995]
 [10.0093   6.68385  0.87    11.0998 ]]


In [ ]:
#TRANSFORMES hugging face and all the models in one place plus source of the python code of
#the models and applictions
